### ISSUE TITLE
help

### ISSUE THREAD

**Issue by JohnnyJosda** [40163650/FSRForReShade#2]
How should I use it in Reshade?

**Comment by 40163650** [comment]
![image](https://github.com/user-attachments/assets/3047db0e-6d5a-4359-9dca-ad0d325d65c4)
Copy the file here

![image](https://github.com/user-attachments/assets/fc7f7977-1dbb-4951-b7bf-ee50e242e921)
Add this line here

![image](https://github.com/user-attachments/assets/83ab0bc5-0b62-4942-bc94-d48d89be2f44)
Add these lines here

Please note - this is intended to be used as anti-aliasing for games that don't have it. It will not speed up your game, if anything it will slow it down.

**Comment by JohnnyJosda** [comment]
Can I use it for games in DX12?

**Comment by 40163650** [comment]
That's more a compatibility issue for ReShade.

The version of ReShade I designed it for only went up to DirectX11.

There may be a new version of ReShade that does work with DX12. Like I say
in the ReadMe, if you're using a newer version of ReShade, you may have to
change the bits where it says FullscreenTriangle in the shader
[image: image.png]
with PostProcessVS

Otherwise, I don't see why it wouldn't work, but I haven't tried it.

Hope this helps.

**Comment by ajaxnotmeta** [comment]
im all confused with this thing, can you give a more thorough docuentation?
this shaders seems to be useful for anything as how CAS is that was included in SweetFX github repos, and for some reason the only thing you put in readme was something wholy alien compared to what Reshade i know lol, not to mention that SweetFX seems to be an ancient remnants too on a completely Old game(that may also supported with Lastest Reshade tbh)
as i am also eager to use this software on Phantasy Star Universe Clementine and Phantasy Star Universe : AOTI using Lastest Reshade to spice things up and NOT(and even dont care) aobout EA Games named NFS:Underground

**Comment by 40163650** [comment]
I used to use SweetFX on Rainbow 6 Siege, so it does work for newer games too, NFSU2 was just an example.

I just tried out the new version of ReShade to see how it works.

Seems they renamed some things, but it works in pretty much the same way as it did. If you want to use my shader, just put it in the `reshade-shaders\Shaders` folder, and rename it from `.h` to `.fx` and it might work.

Since CAS is included in the new version you might as well use that instead though.

**Comment by ajaxnotmeta** [comment]
> I used to use SweetFX on Rainbow 6 Siege, so it does work for newer games too, NFSU2 was just an example.
> 
> I just tried out the new version of ReShade to see how it works.
> 
> Seems they renamed some things, but it works in pretty much the same way as it did. If you want to use my shader, just put it in the `reshade-shaders\Shaders` folder, and rename it from `.h` to `.fx` and it might work.
> 
> Since CAS is included in the new version you might as well use that instead though.

ah i see.. thank you for replying my comments, but that CAS shader are only implements CAS without upscaler

**Comment by 40163650** [comment]
> ah i see.. thank you for replying my comments, but that CAS shader are only implements CAS without upscaler

Maybe I wasn't clear enough in the read-me. The upscaler in my shader takes the output of the game at whatever resolution you set it to in the game, then shrinks it down to 1080p, then scales it back up using FSR to the original size.

It cannot change the size of the window before anything is rendered, so it will not create any speed-ups. In fact, it will slow it down (though not by any noticeable amount.)

So, in effect, my shader acts like a type of anti-aliasing. It was also kind of a proof of concept, to see if I could do it, an academic exercise... I didn't think anyone would actually try to use it :/

This is why I recommended using CAS, because that is also a type of anti-aliasing, and since it comes with re-shade, it should work without any tweaks. But if you are looking to change the resolution of the game, you will have to find something else to do it such as NVidia Inspector or RadeonMod (depending on your GPU).
